### PR TITLE
Add new GUI entry in lighttable for renaming tags

### PR DESCRIPTION
**Pull request by GHswitt**
Rename tag: A new tag is added to all images containing old tag. After that, the old tag is removed from all images (and removed from tags). The GUI entry has two entries: Old tag, New tag and a Go button.

### CODE REVIEW

**Comment by GHswitt** [comment]
Just found out that it updates the image tags in the database, but the XMP files are not updated automatically. The XMP has still the old value in it. Only when I open an image in darkroom and switch back to lighttable, the new tag from the database gets written to the XMP. How can I do that from LUA?

**Comment by supertobi** [comment]
For me this sounds like a bug. @boucman what do you think?

**Comment by houz** [comment]
Maybe we should wire dt_tag_reorganize() into the Lua API instead – and check if it actually works as it's unused in current dt. 😄

**Comment by chrik5** [comment]
Definitly, yes. This will make the proposed script very short. 
Finally, I will be able to fix all my tag typos. Thx @GHswitt for starting this!

**Comment by GHswitt** [comment]
No problem, I just needed a way to do renaming more comfortable.

**Comment by GHswitt** [comment]
I looked into dt_tag_reorganize, but couldn't find where it synchronizes the new tags to the XMP. Can anyone give me a hint?

**Comment by GHswitt** [comment]
As far as I can see it, dt_control_write_sidecar_files() or dt_image_write_sidecar_file should also be available via Lua API.

**Comment by houz** [comment]
It doesn't. It's been bitrotting for years.

**Comment by boucman** [comment]
* feature freeze, no new api (obviously)
* even if we wire a tag renaming primitive in lua, we need to figure out what's going on with the XMP. this is a bug, your code should work
* maybe DT needs a core way to rename tags ?

**Comment by spaceChRiS** [comment]
Maybe that's the right time and place to start another discussion regarding the topic. Renaming tags is a feature I am looking for as well. But it is something that I would need several times a year, but not very often. This is something that would perfectly fit into a regular menu structure, that darktable avoids so far. But that may not be a necessary restriction for lua scripts. For the functionality of tag renaming, I think about a menu entry “Rename tag” that opens a little window with a search text entry field, a list of tags found, where one tag could be marked, a text entry field that gives the new tag and an “apply” button. A new module that is always visible, at minimum in the collapsed state, does IMO not really fit to the purpose of the functionality of tag renaming.

**Comment by supertobi** [comment]
FYI
darktable 2.2.2 released:
https://www.darktable.org/2017/01/darktable-2-2-2-released/

Bugfixes:
...
* Lua: sync XMPs after some tag manipulations

...

**Comment by supertobi** [comment]
I'm going through all the PRs. Any news here?

**Comment by GHswitt** [comment]
Not from my side. I'm still using rename-tags.lua, works ok.

**Comment by supertobi** [comment]
OK, then I'll pull this script.

**Pull request merged**
