### PR TITLE
Delete compiled .mo files

### PR DESCRIPTION
**Pull request by simon04**

### CODE REVIEW

**Comment by supertobi** [comment]
I think we should not delete the .mo files until we have a make file (or a script, or something like that) to generate them.

**Comment by supertobi** [comment]
And if we remove the .mo files we will need some kind of release press, because it is then no longer possible to just clone the git repro and use the scripts.

**Comment by wpferguson** [comment]
We probably need to do press releases anyway to let people know what's there.  I could tweak script_manager to automatically regenerate the .mo files on update.

**Comment by wpferguson** [comment]
@supertobi PR 148 has the translation tool, tools/gen_i18n_mo.lua to generate the .mo files and put them in the proper location.  What are your thoughts?

**Comment by supertobi** [comment]
The script is a nice and welcome improvement. But I'm not sure what to do next. :(

**Comment by wpferguson** [comment]
The only script supplying mo files is contrib/select_untagged.lua.  We could just leave this as is for the moment, and merge the translation tool.  Once the translation tool has been used for awhile, we can merge this and let the translation tool take over generating this mo file too.

**Comment by supertobi** [comment]
OK, then lets keep this .mo files for now. I think the best time for removing them is the next dt release Then we could add a note to the release notes.

**Pull request merged**
