### PR TITLE
Update kml_export.lua - use os.remove(image)

### PR DESCRIPTION
**Pull request by supertobi**
use os.remove(image)

### CODE REVIEW

**Comment by boucman** [comment]
that sound like a regression to me... yield is the proper way to do this...

**Comment by supertobi** [comment]
Why us yield better then os.remove()?

**Comment by boucman** [comment]
hmm, no you're right os.remove should be ok. yield has the benifit of not blocking the lua thread, but unless you remove a network file, that should be fine

**Comment by supertobi** [comment]
OK, fine, then please push

**Pull request merged**
